; Mega Man X (Legacy Collection ROM, US 1.0 code) - battery save patch.
;
; The game state lives in $7E1F7A-$7E1F9C: stage select cursor, fortress
; progress, Hadouken, lives, sub tanks, weapons, armor, heart tanks, max HP
; and the intro-cleared flag. New game clears exactly this range.
;
; Saving: every time the stage select screen opens (after the intro stage,
; a cleared stage, an exit or a game over), the block is written to battery
; SRAM. The attract demo never reaches stage select.
;
; Loading goes through TITLE > PASS WORD. The entry screen normally starts
; from the last password shown ($7EFFCB, 12 digits). When a save exists the
; patch fills it with a password generated by the game's own encoder from
; the saved block. Confirming that password unchanged then restores the whole
; block, including what passwords drop: lives, sub tank energy, the Hadouken
; and fortress progress. A typed password works as in the original game.
;
; SRAM layout (8 KB at $70:0000; the game's own debug code bumps $70000D):
;   two slots at $700100 and $700180, written alternately:
;     +0 "MMXS"  +4 sequence  +6 sum16 of data  +8 data (35 bytes)
;   $700300  prefilled password (12 digits), $70030C prefill flag
;   $700310  temp words
;   $700320  backup of the live block while the encoder runs

lorom

!SLOT0    = $700100
!SLOT1    = $700180
!SLOTSTEP = $0080
!BLK      = $1F7A        ; progress block in bank $7E
!BLKLEN   = $0023
!PREFILL  = $700300
!PFLAG    = $70030C
!TMP      = $700310
!TMP2     = $700312
!BACKUP   = $700320
!RTL80    = $87AF        ; a $6B byte in bank $80, used as an RTL trampoline

; ---- header: ROM + RAM + battery, 8 KB SRAM ----
org $00FFD6
    db $02
org $00FFD8
    db $03

; ---- copy protection ----
; The game writes a value to the SRAM area and reads it back. On the
; original cartridge there is no SRAM there, the compare fails and a counter
; decays to 0. With SRAM the compare succeeds and the counter climbs, which
; later cripples the game. Each probe below becomes a branch straight to its
; "no SRAM" path, so it neither writes SRAM nor detects it. Tamper checks
; elsewhere compare single bytes of these routines (the INC, BPL and BEQ
; opcodes, $81853B and the bank bytes at $849D0A/$849D0E); none of those
; bytes change.

org $81816B              ; every frame: STA $700800 / CMP, counter $83
    bra dec_83
org $818175
dec_83:
org $818526              ; falling: STA $700804 / CMP, counter $1F9E
    bra dec_fall
org $818530
dec_fall:
org $849D07              ; taking damage: STA $700505 / CMP, counter $1F9F
    bra dec_damage
org $849D11
dec_damage:
org $84A46D              ; enemy destroyed: STA $701000 / CMP, counter $1F9D
    bra dec_enemy
org $84A477
dec_enemy:

; ---- hooks (all sites run with 8-bit A/X/Y and D = $1E48) ----
org $80BCF7              ; stage select opens: replaces LDA #$02 : STA $01
    jsl save_hook
org $80EF2C              ; password entry opens: replaces STZ $04 : STZ $07
    jsl pw_open
org $80EF9E              ; password accepted: replaces LDA #$06 : STA $01
    jsl pw_accept

; ---- new code in unused space in bank $AB ----
org $AB8000

save_hook:
    php
    rep #$30
    pha
    phx
    phy
    phb
    jsr do_save
    plb
    ply
    plx
    pla
    plp
    lda #$02
    sta $01
    rtl

; Write the live block into the older SRAM slot. 16-bit A/X/Y.
do_save:
    jsr find_newest
    bcs .have
    ldx #$0000
    lda #$0000
    bra .write
.have
    lda.l !SLOT0+4,x
    inc a
    pha
    txa
    eor #!SLOTSTEP
    tax
    pla
.write
    sta.l !TMP2
    lda #$0000
    sta.l !SLOT0+0,x         ; invalidate the target slot first
    sta.l !SLOT0+2,x
    lda.l !TMP2
    sta.l !SLOT0+4,x
    phx
    phb
    txa
    clc
    adc.w #!SLOT0+8
    tay
    ldx #!BLK
    lda #!BLKLEN-1
    db $54,$70,$7E           ; MVN $7E -> $70
    plb
    plx
    jsr slot_sum
    sta.l !SLOT0+6,x
    lda #$4D4D               ; "MM"
    sta.l !SLOT0+0,x
    lda #$5358               ; "XS"
    sta.l !SLOT0+2,x
    rts

; X = slot offset. Returns A = 16-bit byte sum of the slot data, X kept.
slot_sum:
    phx
    lda #$0000
    sta.l !TMP
    ldy #!BLKLEN
.loop
    lda.l !SLOT0+8,x
    and #$00FF
    clc
    adc.l !TMP
    sta.l !TMP
    inx
    dey
    bne .loop
    plx
    lda.l !TMP
    rts

; X = slot offset. Carry set if the slot holds a valid save.
slot_valid:
    lda.l !SLOT0+0,x
    cmp #$4D4D
    bne .no
    lda.l !SLOT0+2,x
    cmp #$5358
    bne .no
    jsr slot_sum
    cmp.l !SLOT0+6,x
    bne .no
    sec
    rts
.no
    clc
    rts

; Carry set and X = offset of the newest valid slot; carry clear if none.
find_newest:
    ldx #$0000
    jsr slot_valid
    bcc .only1
    ldx #!SLOTSTEP
    jsr slot_valid
    bcc .pick0
    lda.l !SLOT1+4
    sec
    sbc.l !SLOT0+4
    beq .pick0
    bmi .pick0
    ldx #!SLOTSTEP
    sec
    rts
.pick0
    ldx #$0000
    sec
    rts
.only1
    ldx #!SLOTSTEP
    jmp slot_valid

; Emulate JSR $F0A6 (password encoder, bank $80) from this bank. The encoder
; needs 8-bit A/X/Y, D = $1E48 and a data bank that maps ROM at $BD24.
call_encoder:
    sep #$30
    phk
    pea.w enc_ret-1
    pea.w !RTL80-1
    jml $80F0A6
enc_ret:
    rep #$30
    rts

; Password entry opens: if a save exists, generate its password into
; $7EFFCB (which the screen copies into its digits next) and remember it.
pw_open:
    php
    rep #$30
    pha
    phx
    phy
    lda #$0000
    sta.l !PFLAG
    jsr find_newest
    bcc .out
    phx
    phb
    ldx #!BLK                ; back up the live block
    ldy.w #!BACKUP
    lda #!BLKLEN-1
    db $54,$70,$7E           ; MVN $7E -> $70
    plb
    plx
    phb
    txa                      ; put the saved block in place
    clc
    adc.w #!SLOT0+8
    tax
    ldy #!BLK
    lda #!BLKLEN-1
    db $54,$7E,$70           ; MVN $70 -> $7E
    plb
    jsr call_encoder
    phb
    ldx.w #!BACKUP           ; restore the live block
    ldy #!BLK
    lda #!BLKLEN-1
    db $54,$7E,$70
    plb
    ldx #$0000
.copy
    lda.l $7EFFCB,x
    sta.l !PREFILL,x
    inx
    inx
    cpx #$000C
    bne .copy
    lda #$0001
    sta.l !PFLAG
.out
    ply
    plx
    pla
    plp
    stz $04
    stz $07
    rtl

; Password accepted and decoded into the live block. If it is the unchanged
; prefilled one, overwrite the block with the full save.
pw_accept:
    php
    rep #$30
    pha
    phx
    phy
    lda.l !PFLAG
    beq .out
    lda #$0000
    sta.l !PFLAG
    ldx #$0000
.cmp
    lda.l $7E1E60,x          ; entered digits (D = $1E48, offset $18)
    cmp.l !PREFILL,x
    bne .out
    inx
    inx
    cpx #$000C
    bne .cmp
    jsr find_newest
    bcc .out
    phb
    txa
    clc
    adc.w #!SLOT0+8
    tax
    ldy #!BLK
    lda #!BLKLEN-1
    db $54,$7E,$70           ; MVN $70 -> $7E
    plb
.out
    ply
    plx
    pla
    plp
    lda #$06
    sta $01
    rtl
